"""Opt in with LINKHUB_TEST_DB=1 against the migrated local database.

Each test rolls back its rows. PostgreSQL identity sequences can still advance.
"""

import os
from uuid import uuid4

import pytest
from sqlalchemy import insert
from sqlalchemy.exc import IntegrityError

from app.db import get_engine
from app.models import Link, User

pytestmark = pytest.mark.skipif(
    os.getenv("LINKHUB_TEST_DB") != "1", reason="requires migrated local PostgreSQL"
)


@pytest.fixture
def connection():
    with get_engine().connect() as conn:
        transaction = conn.begin()
        try:
            yield conn
        finally:
            transaction.rollback()


def add_user(connection, email=None):
    return connection.execute(
        insert(User).values(
            email=email or f"{uuid4().hex}@example.test", password_hash="test-only"
        ).returning(User.id)
    ).scalar_one()


def test_duplicate_email_is_rejected(connection):
    email = f"{uuid4().hex}@example.test"
    add_user(connection, email)
    with pytest.raises(IntegrityError):
        with connection.begin_nested():
            add_user(connection, email)


def test_link_cannot_reference_missing_user(connection):
    # Negative IDs are never generated by the normal identity sequence.
    with pytest.raises(IntegrityError):
        with connection.begin_nested():
            connection.execute(insert(Link).values(user_id=-1, destination_url="https://example.com"))


def test_required_destination_is_enforced(connection):
    user_id = add_user(connection)
    with pytest.raises(IntegrityError):
        with connection.begin_nested():
            connection.execute(insert(Link).values(user_id=user_id, destination_url=None))


def test_link_defaults_and_multiple_links_per_user(connection):
    user_id = add_user(connection)
    rows = []
    for _ in range(2):
        rows.append(connection.execute(
            insert(Link).values(user_id=user_id, destination_url="https://example.com")
            .returning(Link.id, Link.is_active, Link.expires_at, Link.created_at)
        ).one())
    assert rows[0].id != rows[1].id
    assert all(row.is_active is True and row.expires_at is None for row in rows)
    assert all(row.created_at.tzinfo is not None for row in rows)
